### ISSUE TITLE
BXtendDSL solution: improve documentation

### ISSUE THREAD

**Issue by agarciadom** [agarciadom/benchmarx#6]
I was trying out the BXtendDSL solution today, and I ran into a few niggles to get it started. The README.md does not provide clear instructions to build the solution. @tbuchmann - could you clarify what to install from which update site(s)? I've seen these two in your website:

* [BXtend update site](https://tbuchmann.github.io/bxtendUpdateSite/)
* [BXtendDSL update site](https://tbuchmann.github.io/bxtendDSLUpdateSite/)

Does the BXtendDSL update site include BXtend itself?

**Comment by agarciadom** [comment]
I also ran into some trouble locating the specific files which needed tweaking according to the README.md file. The project has a somewhat complicated build process, with `src`, `BXtend`, `src-gen`, and `xtend-gen` folders. I had to `grep` around to find that the files to modify were in the `src-gen` folder. Can you mention this in the README?

**Comment by agarciadom** [comment]
Finally, is there any way to temporarily disable the code generation after the manual fixes have been applied, to avoid losing those customisations?

**Comment by tbuchmann** [comment]
Sorry, I thought that including the required plugins/update sites to the target file would be enough...

You need to install BXtendDSL from this site: 

https://tbuchmann.github.io/bxtendDSLUpdateSite/

In the Eclipse Install Software Dialog, uncheck the checkbox "Show only the latest versions of available software" and select Version 1.0.0.202305311643

To temporarily disable the code generation, disable "Build automatically" in Eclipse. Each auto build triggers the code generation (as this is the standard behavior of Xtext projects).

I updated the README.md accordingly and created a new pull request.

**Comment by agarciadom** [comment]
Thank you! I've merged your PR.
