### ISSUE TITLE
NMF solution: failed compilation

### ISSUE THREAD

**Issue by agarciadom** [agarciadom/benchmarx#8]
I have tried building the NMF solution myself, and the provided command (`dotnet build -c Release nmf.csproj`) produces compilation errors. See the attached file:

[nmf-error-log.txt](https://github.com/agarciadom/benchmarx/files/12061783/nmf-error-log.txt)

Looking at the project, it seems to refer to locally-built NMF binaries, instead of fetching them from the internet (e.g. via NuGet). @georghinkel can you update the instructions to show how to do this? Ideally, it should be possible to build your solution via Docker, to avoid having to locally install a specific version of the .NET SDK.

**Comment by agarciadom** [comment]
I've pushed in bb5d866 some changes to use the NuGet packages for NMF, and it seems to build now.

**Comment by agarciadom** [comment]
I've updated the README to reflect these commands. Can you confirm if this will produce the same results as in your paper?

**Comment by georghinkel** [comment]
Yes, it does. Sorry, I forgot that. Assembly references are usually nicer for debugging purposes.

**Comment by georghinkel** [comment]
The only thing, the NMF-Dynamics reference is a bit odd, because the solution does not make use it, but it does use the repository package which comes as a requirement. The more typical setting would be referencing the NMF-Basics package.

**Comment by agarciadom** [comment]
Thanks for confirming! Could you send a PR with the updated references when you can?

**Comment by georghinkel** [comment]
@agarciadom I created #11 just now. This PR fixes all the test failures in the NMF solutiuon, of course only for the one ignoring order.
