### ISSUE TITLE
YAMTL solution: failed compilation

### ISSUE THREAD

**Issue by agarciadom** [agarciadom/benchmarx#9]
I've tried building the YAMTL solution, and I'm running into errors:

```shell
~/Documents/benchmarx/examples/containerstominiyaml/implementationArtefacts/emf-syncer_ttc2023_container2miniyaml$ ./gradlew build
Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details

> Task :compileJava
/home/agd516/Documents/benchmarx/examples/containerstominiyaml/implementationArtefacts/emf-syncer_ttc2023_container2miniyaml/src/main/java/containerstominiyaml/yamtl/YAMTLContainersToMiniYAML_BXTool.java:115: error: cannot find symbol
                        xformForward = new YAMTLContainersToMiniYAML(ContainersPackage.eINSTANCE, MiniyamlPackage.eINSTANCE);
                                           ^
  symbol:   class YAMTLContainersToMiniYAML
  location: class YAMTLContainersToMiniYAML_BXTool
/home/agd516/Documents/benchmarx/examples/containerstominiyaml/implementationArtefacts/emf-syncer_ttc2023_container2miniyaml/src/main/java/containerstominiyaml/yamtl/YAMTLContainersToMiniYAML_BXTool.java:207: error: cannot find symbol
                        xformBackward = new MiniYAML2Containers(MiniyamlPackage.eINSTANCE, ContainersPackage.eINSTANCE);
                                            ^
  symbol:   class MiniYAML2Containers
  location: class YAMTLContainersToMiniYAML_BXTool
2 errors

> Task :compileJava FAILED

FAILURE: Build failed with an exception.
```

@arturboronat, can you check what may be happening? I'd like to be able to independently obtain correctness and performance results, so we can do a fair comparison across all solutions.

**Comment by agarciadom** [comment]
It seems like the project has a mix of `.java` and `.groovy` files in the same source folder. For this to work in plain Gradle, outside of Eclipse, it's best to rename `src/main/java` to `src/main/groovy` so the Groovy plugin is entirely responsible for compilation.

**Comment by agarciadom** [comment]
I had to install the [Groovy-Eclipse plugins](https://github.com/groovy/groovy-eclipse/wiki#how-to-install) matching my exact Eclipse release to avoid compilation errors from your `.groovy` files from Eclipse (main package and Groovy 4.0 compiiler).

Could you provide some information on how to set up a development environment for your solution in your README?

**Comment by agarciadom** [comment]
Just so you know, I rearranged your code to split it into src/main/groovy and src/test/groovy. That makes a standard Gradle build Just Work (TM), and tests are also implicitly run with `./gradlew test`.

**Comment by arturboronat** [comment]
Thanks, @agarciadom 

I believe there was no requirement for the solutions to run from command line as the benchmark tests are run from within the Eclipse JUnit launcher. 

Is there a way to execute the benchmark from command line?

**Comment by agarciadom** [comment]
No problem. I had to run the benchmark for YAMTL from the command line as I was still getting a spurious compilation error from the Groovy-Eclipse integration, which wasn't being reported by a simple `./gradlew test`, and I did not see any instructions on how to set that up in the README.

I added a custom task to your Gradle build to run the benchmark from the command line. You should be able to do this:

```
./gradlew runScalabilityTest
```
